services:
  api:
    image: "getmeili/meilisearch:v1.7"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    environment:
      MEILI_MASTER_KEY: "T35T-M45T3R-K3Y"

volumes:
  meili_data:
